apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur
  namespace: devsecops-demo
spec:
  refreshInterval: 10s
  secretStoreRef:
    # This name must match the metadata.name in the SecretStore
    name: conjur
    kind: SecretStore
  data:
  - secretKey: user
    remoteRef:
      key: VaultDemo/LOB_Demo/Safe-Appl-SecretTest/devsecops_demo_dual/username
  - secretKey: psw
    remoteRef:
      key: VaultDemo/LOB_Demo/Safe-Appl-SecretTest/devsecops_demo_dual/password     