services:
  conjur-cli:
    build: .
    volumes:
      - ./devops:/root
      - ./config:/root/.kube/config               
    stdin_open: true
    tty: true
    restart: "no" 
    working_dir: /root

volumes:
  pgdata: {}
