
#conjur policy load -f cg-secrets.yml -b root

- &variables
    - !variable SPECTRAL_DSN
    - !variable CG_API_KEY
    - !variable CG_API_SECRET
    - !variable ENVIRONMENT_ID   
- !permit
    role: !host github-apps
    privilege: [ read, execute ]
    resource: *variables