# conjur policy load -f grant-secrets-access.yaml -b root
- !grant
  role: !group eso/delegation/consumers
  member: !host app-path/system:serviceaccount:devsecops-demo:devsecops-demo

- !grant
  role: !group VaultDemo/LOB_Demo/Safe-Appl-SecretTest/delegation/consumers 
  member: !host app-path/system:serviceaccount:devsecops-demo:devsecops-demo