apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsecops-demo
  namespace: devsecops-demo
---
# ruolo per il service account 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: devsecops-demo
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: devsecops-demo
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: devsecops-demo
    name: devsecops-demo
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access  