env:
    SYSDIG_SECURE_ENDPOINT: "https://eu1.app.sysdig.com"
    REGISTRY_HOST: "quay.io"
    IMAGE_NAME: "dgsspa/sysdig_test"
    IMAGE_TAG: "tag" 
    DOCKERFILE_CONTEXT: "./cicd"
    REGISTRY_USER: "user"

name: Test connection to the cluster

on: [push]

jobs:
  release:
   runs-on: self-hosted
   steps:
    - name: Update Kubernetes deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG2 }}
        #KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
      with:
        args: get pods