name: CloudGuard | IAC scan

on:
  workflow_dispatch:

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}    

jobs:
  iac-scan:
   runs-on: self-hosted
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set commit hash as environment variable
      run: env 
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v2
      with:
        spectral-dsn: ${{ secrets.URL }}
        # spectral-args: scan --engines oss,iac,secrets
        spectral-args: scan --engines iac,secrets --ok