name: CloudGuard | IAC scan

on:
  workflow_dispatch:

jobs:
  iac-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and run Spectral CI
        uses: spectralops/spectral-github-action@v2
        env:
          SPECTRAL_DSN: dsn://spu-ab55699b539a418cbcfc4259d393505e@eu.api.spectralops.io
        with:
          spectral-args: scan --engines iac,secrets --ok
