name: Release FE

on:
  workflow_dispatch:

jobs:
  release:
   runs-on: self-hosted
   steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
      uses: cyberark/conjur-action@v2.0.5
      with:
        url: https://conjur-cluster.lab
        account: dgsspa
        host_id: host/github-apps
        api_key: ${{ secrets.CONJUR_API_KEY }}
        secrets: github-apps/KUBE_CONFIG|KUBE_CONFIG;github-apps/github_password|github_password;
        certificate: ${{ secrets.CONJUR_CERTIFICATE }}    

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: giacomodevopsdgs
        password: ${{ env.GITHUB_PASSWORD }}

    - name: Set commit hash as environment variable
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ghcr.io/giacomodevopsdgs/demo_frontend:${{ env.COMMIT_HASH }}

    - name: Update Kubernetes deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ env.KUBE_CONFIG }} #credo sia superfluo se lo prende dall'env
      with:
        args: set image deployment/frontend frontend=ghcr.io/giacomodevopsdgs/demo_frontend:${{ env.COMMIT_HASH }} --namespace=devsecops-demo --record

    - name: RollOut Kubernetes deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ env.KUBE_CONFIG }} #credo sia superfluo se lo prende dall'env
      with:
        args: rollout restart deployment/frontend --namespace=devsecops-demo 
  
    # - name: Update Kubernetes deployment
    #   uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ env.KUBE_CONFIG }} #credo sia superfluo se lo prende dall'env
    #   with:
    #     args: get pods