name: Deploy to Kubernetes

on:
  push:
    tags:
      - '*' 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: https://conjur-cluster.lab
          account: dgsspa
          host_id: host/github-app
          api_key: ${{ secrets.CONJUR_API_KEY }}
          secrets: secrets/KUBE_CONFIG|KUBE_CONFIG
          certificate: ${{ secrets.CONJUR_CERTIFICATE }}

      - name: Decode KUBE_CONFIG and set up kubectl
        run: |
          echo "${{ env.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}

      - name: Update Kubernetes deployment
        uses: actions-hub/kubectl@master
        with:
          args: set image deployment/frontend frontend=ghcr.io/giacomodevopsdgs/demo_frontend:${{ github.sha }} --namespace=devsecops-demo --record
