name: Test connection to the cluster

on: [push]

jobs:
  release:
   runs-on: self-hosted
   steps:
    - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
      uses: cyberark/conjur-action@v2.0.5
      with:
        url: https://conjur-cluster.lab
        account: dgsspa
        host_id: host/github-apps
        api_key: ${{ secrets.CONJUR_API_KEY }}
        secrets: github-apps/KUBE_CONFIG1|KUBE_CONFIG;
        certificate: ${{ secrets.CONJUR_CERTIFICATE }}    
    # - name: Update Kubernetes deployment
    #   uses: actions-hub/kubectl@master
    #   # env:
    #   #   KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
    #   with:
    #     args: get ns