name: Test connection to the cluster

on: [push]

jobs:
  release:
   runs-on: self-hosted
   steps:
    - name: Update Kubernetes deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        #KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
      with:
        args: get pods